### ISSUE TITLE
Liệu giá trị n của bạn có thể có giá trị âm được k ?

### ISSUE THREAD

**Issue by toniminh161200** [20021423/btvn-on-basic-bec-17#2]
https://github.com/20021423/btvn-on-basic-bec-17/blob/43b30cac324824eef8494b5beb9f5879b31c8046/bai1.cpp#L22

**Comment by 20021423** [comment]
e đã hiểu, e sẽ sửa thành 
do
{
cout <<"Nhap n khong am: ";
cin>>n;
}while(n<0);
