### ISSUE TITLE
Mục đích của dòng này nghĩa là gì vậy bạn ?

### ISSUE THREAD

**Issue by toniminh161200** [20021423/btvn-on-basic-bec-17#4]
https://github.com/20021423/btvn-on-basic-bec-17/blob/43b30cac324824eef8494b5beb9f5879b31c8046/bai4.cpp#L9

**Comment by 20021423** [comment]
dòng đấy là toán tử 3 ngôi viết thay cho if(n<0) thì n=-n; để n dương còn cho vào vòng lặp while(n>0) đc ấy ạ. Nếu không có dòng đấy gặp TH số âm thì không tính đc số chữ số đc ạ
